In [1]:
import pandas as pd

df = pd.read_csv('_2025_PayPal_.csv')

# COMPLETED transactions money coming in

In [2]:
# remove commas BEFORE converting
df['Amount'] = df['Amount'].astype(str).str.replace(',', '')

# convert to numeric
df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')

# filter completed
df_completed = df[df['Status'] == 'Completed'].copy()

# money in
df_in = df_completed[df_completed['Amount'] > 0].copy()

In [20]:
# sort biggest first
df_in = df_in.sort_values(by='Amount', ascending=False).reset_index(drop=True)

# total
total_in = df_in['Amount'].sum()

# remove dad transactions
df_in_clean = df_in[
    ~df_in['Name'].str.contains('Erich Luckerbauer', case=False, na=False)
].copy()

# recompute total
total_in_clean = df_in_clean['Amount'].sum()

print("TOTAL INCOME (CLEAN):", total_in_clean)
# df_in_clean

TOTAL INCOME (CLEAN): 2270.79

# DEDUCTIONS

In [21]:
# money out (expenses)
df_out = df_completed[df_completed['Amount'] < 0].copy()

In [22]:
df_out['Amount_abs'] = df_out['Amount'].abs()

In [23]:
total_out = df_out['Amount'].sum()
print("TOTAL EXPENSES:", total_out)
print("TOTAL EXPENSES (ABS):", df_out['Amount'].abs().sum())

TOTAL EXPENSES: -23801.489999999998
TOTAL EXPENSES (ABS): 23801.489999999998

# DEDUCTIONS - bandcamp - beatport

In [31]:
bandcamp_total = df_out[df_out['Name'].str.contains('Bandcamp', case=False, na=False)]['Amount'].abs().sum()
print(f"2025: ${bandcamp_total:,.2f} spent on songs via Bandcamp")

# export 
import openpyxl
df_bc = df_out[df_out['Name'].str.contains('Bandcamp', case=False, na=False)].copy()

file_path = "/Users/yerik/Library/Mobile Documents/com~apple~CloudDocs/_YDB_/_4_yy_icloud/_yy6_LEGAL/_iii_LEGAL_KATIE_FISH/1_KIMVA_DOCS_together/_ii_TAXES_receipts/_2025_taxes/Deductions_1.xlsx"

with pd.ExcelWriter(file_path, engine="openpyxl", mode="a", if_sheet_exists="replace") as writer:
    df_bc.to_excel(writer, sheet_name="band_camp", index=False)

2025: $348.81 spent on songs via Bandcamp

In [32]:
beatport_total = df_out[df_out['Name'].str.contains('Beatport', case=False, na=False)]['Amount'].abs().sum()
print(f"2025: ${beatport_total:,.2f} spent on songs via Beatport")

# export Beatport

import openpyxl

df_bp = df_out[df_out['Name'].str.contains('Beatport', case=False, na=False)].copy()

file_path = "/Users/yerik/Library/Mobile Documents/com~apple~CloudDocs/_YDB_/_4_yy_icloud/_yy6_LEGAL/_iii_LEGAL_KATIE_FISH/1_KIMVA_DOCS_together/_ii_TAXES_receipts/_2025_taxes/Deductions_1.xlsx"

with pd.ExcelWriter(file_path, engine="openpyxl", mode="a", if_sheet_exists="replace") as writer:
    df_bp.to_excel(writer, sheet_name="beatport", index=False)

2025: $3,776.18 spent on songs via Beatport

#### just export those two df - two more pages in excel

# SOOJIN KIM sent household

In [13]:
df_soojin = df_out[df_out['Name'].str.contains('Soo Kim', case=False, na=False)].copy()
soojin_total = df_soojin['Amount'].abs().sum()
print(f"2025: ${soojin_total:,.2f} paid to Soojin")

2025: $10,686.00 paid to Soojin

##### export sooj paypal money excahneg 2025

In [35]:
df_soojin .to_csv("/Users/yerik/Library/Mobile Documents/com~apple~CloudDocs/_YDB_/_4_yy_icloud/_yy6_LEGAL/_iii_LEGAL_KATIE_FISH/1_KIMVA_DOCS_together/_25_DOCUMENTS/_25_income_statements_both/PayPal_money_exchange_all_2025.csv", index=False)

In [23]:
# REMOVE band camp and beatport soojin

In [16]:
df_out_clean = df_out[
    ~df_out['Name'].str.contains('Bandcamp|Beatport|soo', case=False, na=False)
].sort_values(by='Amount', ascending=True).reset_index(drop=True)

df_left = df_out_clean['Amount'].abs().sum()
df_left

np.float64(8990.5)

In [18]:
df_out_clean
df_out_clean.to_csv("df_out_clean.csv", index=False)

# end

In [8]:
df = df[df['Status'] == 'Completed']

In [10]:
df_bandcamp = df[df['Name'] == 'Bandcamp Ventures LLC']

In [11]:
df_bandcamp

,Date,Time,TimeZone,Name,Type,Status,Currency,Amount,Fees,Total,Exchange Rate,Receipt ID,Balance,Transaction ID,Item Title
14,02/03/2025,12:45:46,PST,Bandcamp Ventures LLC,Express Checkout Payment,Completed,USD,-2.00,0.0,-2.00,NaN,NaN,-2.00,2D144444097948505,NaN
16,02/03/2025,13:18:44,PST,Bandcamp Ventures LLC,Express Checkout Payment,Completed,EUR,-1.03,0.0,-1.03,NaN,NaN,-1.03,8F698770GP618125F,NaN
54,03/31/2025,17:27:16,PDT,Bandcamp Ventures LLC,Express Checkout Payment,Completed,USD,-10.00,0.0,-10.00,NaN,NaN,-10.00,17V58970D98196005,NaN
56,03/31/2025,17:29:12,PDT,Bandcamp Ventures LLC,Express Checkout Payment,Completed,EUR,-10.00,0.0,-10.00,NaN,NaN,-10.00,6PM292137V2027734,NaN
77,04/21/2025,12:42:30,PDT,Bandcamp Ventures LLC,Express Checkout Payment,Completed,USD,-11.00,0.0,-11.00,NaN,NaN,-11.00,7EV76578FM134704D,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,10/27/2025,16:46:31,PDT,Bandcamp Ventures LLC,Express Checkout Payment,Completed,EUR,-1.00,0.0,-1.00,NaN,NaN,-1.00,0HD39473MH182102B,NaN
641,12/27/2025,12:41:30,PST,Bandcamp Ventures LLC,Express Checkout Payment,Completed,USD,-7.00,0.0,-7.00,NaN,NaN,-7.00,5LB93729MW353260U,NaN
643,12/27/2025,12:41:39,PST,Bandcamp Ventures LLC,Express Checkout Payment,Completed,USD,-7.00,0.0,-7.00,NaN,NaN,-7.00,8CE01690PF275780K,NaN
645,12/27/2025,12:41:50,PST,Bandcamp Ventures LLC,Express Checkout Payment,Completed,EUR,-3.00,0.0,-3.00,NaN,NaN,-3.00,71F03074XP2340410,NaN
649,12/27/2025,12:42:00,PST,Bandcamp Ventures LLC,Express Checkout Payment,Completed,EUR,-2.00,0.0,-2.00,NaN,NaN,-2.00,1M566134K2616450K,NaN

In [3]:
df.groupby('Status')['Amount'].agg(['count', 'sum'])

           count                                                sum
Status
Completed    386  -273.15-273.15-1,000.00-180.80-9.21180.80-500....
Pending      267  -273.15273.151,000.009.2125.522.001.12379.01-1...

In [6]:
df['Amount'] = (
    df['Amount']
    .astype(str)
    .str.replace(',', '', regex=False)
)

df['Amount'] = pd.to_numeric(df['Amount'], errors='coerce')

In [7]:
df.groupby('Status')['Amount'].agg(['count', 'sum'])

           count       sum
Status
Completed    386 -15423.32
Pending      267   9250.08