In [8]:
import pandas as pd
# Adjust settings to display all rows and columns
pd.set_option('display.max_rows', None)  # Show all rows
pd.set_option('display.max_columns', None)  # Show all columns
pd.set_option('display.width', 1000)  # Set a wide display width to fit the content
pd.set_option('display.max_colwidth', None)  # Show full column content without truncation

In [2]:
# -----######-----######-----######-----######-----######-----#
# 0_FNS: _dfcat_1704_batch_GET_df_concat_allpkl
# -----######-----######-----######-----######-----######-----#
import os
import pandas as pd
from tqdm import tqdm

def _dfcat_1704_batch_GET_df_concat_allpkl(folder_path):
    """
    Concatenates all PKL files named df_000.pkl to df_036.pkl in the folder.
    
    Parameters:
        folder_path (str): Directory path containing the .pkl files

    Returns:
        pd.DataFrame: Concatenated DataFrame of all valid .pkl files
    """
    dfs = []
    for i in tqdm(range(37), desc="📦 Loading .pkl files"):
        fname = f"df_{i:03d}_.pkl"
        full_path = os.path.join(folder_path, fname)
        if os.path.exists(full_path):
            try:
                df = pd.read_pickle(full_path)
                dfs.append(df)
            except Exception as e:
                print(f"❌ Error reading {fname}: {e}")
        else:
            print(f"⚠️ File not found: {fname}")
    
    if dfs:
        df_concat = pd.concat(dfs, ignore_index=True)
        print(f"✅ Concatenated {len(dfs)} files. Total rows: {len(df_concat)}")
        return df_concat
    else:
        print("❌ No valid .pkl files loaded.")
        return pd.DataFrame()
# Define your directory path containing df_000.pkl to df_036.pkl
folder_path = ""

# Run the function
df_all = _dfcat_1704_batch_GET_df_concat_allpkl(folder_path)

📦 Loading .pkl files: 100%|█████████████████████████████████████████████████| 37/37 [00:00<00:00, 923.25it/s]

✅ Concatenated 37 files. Total rows: 1102

/var/folders/pp/n6z2gh0x56ngpvp6vx5ml9j00000gn/T/ipykernel_39035/3757103639.py:32: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_concat = pd.concat(dfs, ignore_index=True)

In [6]:
df = df_all.copy()

In [7]:
df

,Path,temp_id,file_name,Extension,dur_seconds,dur_min,sr,bit_depth,bit_rate,channels,...,HEX_shape_texture,Path_png_bar_text,spec_centroid_hz,centroid_color,centroid_desc,Path_png_bar_centroid,Path_csv_freq,Path_png_dr,Path_png_id_and_key,audio_hash
0,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2023_this/_...,"TRkw_Back_Seat_ARkw_Anna_Lunoe,_Genesis_Owusu_...","TRkw_Back_Seat_ARkw_Anna_Lunoe,_Genesis_Owusu_...",.aiff,286.875011,4.78125,44100,16,None,2,...,#0039a6,images/text_shape_dy0Fw_bA50.png,3570.460327,#CD7F32,"Ancient, dirty glow",images/centroid_donut_dy0Fw_bA50.png,tables/table_freq_dy0Fw_bA50.csv,images/dbs_plot_dy0Fw_bA50.png,images/key_and_id_dy0Fw_bA50.png,f929d7513e0824451ab22009f5fb180d1444dc5baa7c3a...
1,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2023_this/_...,TRkw_Could_Heaven_Ever_Be_Like_This_ARkw_Idris...,TRkw_Could_Heaven_Ever_Be_Like_This_ARkw_Idris...,.aiff,363.779546,6.062992,44100,16,None,2,...,#001a6e,images/text_shape_dy0Fw_cI64.png,4526.291417,#FFA500,"Assertive, bright",images/centroid_donut_dy0Fw_cI64.png,tables/table_freq_dy0Fw_cI64.csv,images/dbs_plot_dy0Fw_cI64.png,images/key_and_id_dy0Fw_cI64.png,5529059e9612d6b97cc77bcf12dee71e8c983aa9fa642a...
2,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2023_this/_...,TRkw_Disco_Maghreb_ARkw_DJ_Snake_MXkw_Original...,TRkw_Disco_Maghreb_ARkw_DJ_Snake_MXkw_Original...,.aiff,184.799977,3.08,44100,16,None,2,...,#001a6e,images/text_shape_dy3Fw_dD32.png,3876.173475,#CC7722,Muted emotion,images/centroid_donut_dy3Fw_dD32.png,tables/table_freq_dy3Fw_dD32.csv,images/dbs_plot_dy3Fw_dD32.png,images/key_and_id_dy3Fw_dD32.png,b388202ceb4d3f63d7f00c99b6d4f066f882ae4f5cfb61...
3,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2023_this/_...,TRkw_Esa_Nena_ARkw_Chuwe_MXkw_Original_Mix_KYk...,TRkw_Esa_Nena_ARkw_Chuwe_MXkw_Original_Mix_KYk...,.aiff,254.0,4.233333,44100,16,None,2,...,#0039a6,images/text_shape_dy0Fx_eC44.png,3386.507475,#808000,"Tense, decaying",images/centroid_donut_dy0Fx_eC44.png,tables/table_freq_dy0Fx_eC44.csv,images/dbs_plot_dy0Fx_eC44.png,images/key_and_id_dy0Fx_eC44.png,5f0a7a1941e3214a0e2a3266550ceac8250236ef706ade...
4,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2023_this/_...,"TRkw_In_Da_Getto_ARkw_Skrillex,_J_Balvin_MXkw_...","TRkw_In_Da_Getto_ARkw_Skrillex,_J_Balvin_MXkw_...",.aiff,257.28,4.288,44100,16,None,2,...,#001a6e,images/text_shape_dy0Fw_iS45.png,4014.333307,#FF7034,Heated drama,images/centroid_donut_dy0Fw_iS45.png,tables/table_freq_dy0Fw_iS45.csv,images/dbs_plot_dy0Fw_iS45.png,images/key_and_id_dy0Fw_iS45.png,2adba579e83144e7754861a42d55136422ca94c1dece78...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2025_this/_...,TRkw_Transport_ARkw_25_Places_MXkw_Original_Mi...,TRkw_Transport_ARkw_25_Places_MXkw_Original_Mi...,.aiff,402.0,6.7,44100,16,None,2,...,#0039a6,images/text_shape_dy1Et_t271.png,2459.452907,#5C2A9D,Creeping psychedelia,images/centroid_donut_dy1Et_t271.png,tables/table_freq_dy1Et_t271.csv,images/dbs_plot_dy1Et_t271.png,images/key_and_id_dy1Et_t271.png,acbf77829b79298376f1427c084b39477522c35e1844c4...
1098,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2025_this/_...,TRkw_Try_Me_ARkw_Jonathan_Lee_MXkw_Original_Mi...,TRkw_Try_Me_ARkw_Jonathan_Lee_MXkw_Original_Mi...,.aiff,472.075986,7.867933,44100,16,None,2,...,#001a6e,images/text_shape_dy0Et_tJ83.png,4001.985556,#FF7034,Heated drama,images/centroid_donut_dy0Et_tJ83.png,tables/table_freq_dy0Et_tJ83.csv,images/dbs_plot_dy0Et_tJ83.png,images/key_and_id_dy0Et_tJ83.png,05e36e042ac3918a11b405276d940d7e69ce0956bf36b7...
1099,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2025_this/_...,TRkw_Verlucent_ARkw_Za__Paradigma_MXkw_Origina...,TRkw_Verlucent_ARkw_Za__Paradigma_MXkw_Origina...,.aiff,460.165306,7.669422,44100,16,None,2,...,#0039a6,images/text_shape_dy0Et_vZ82.png,3339.297792,#808000,"Tense, decaying",images/centroid_donut_dy0Et_vZ82.png,tables/table_freq_dy0Et_vZ82.csv,images/dbs_plot_dy0Et_vZ82.png,images/key_and_id_dy0Et_vZ82.png,22e01eed99fc5f42a35cd146145de3fc64bc80b4b9dcdf...
1100,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2025_this/_...,TRkw_We_ll_Do_It_ARkw_Setenta_MXkw_Original_Mi...,TRkw_We_ll_Do_It_ARkw_Setenta_MXkw_Original_Mi...,.aiff,177.301723,2.955029,44100,16,None,2,...,#001a6e,images/text_shape_dy3Eu_wS31.png,3464.576967,#808000,"Tense, decaying",images/centroid_donut_dy3Eu_wS31.png,tables/table_freq_dy3Eu_wS31.csv,images/dbs_plot_dy3Eu_wS31.png,images/key_and_id_dy3Eu_wS31.png,3c9b948511cb6f4ae3d33ae3de425d713ae3b0e3661d36...
1101,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2025_this/_...,TRkw_Whatever_It_Takes_ARkw_ILO_MXkw_Original_...,TRkw_Whatever_It_Takes_ARkw_ILO_MXkw_Original_...,.aiff,312.386327,5.206439,44100,16,None,2,...,#0039a6,images/text_shape_dy0Fv_wI55.png,2704.159354,#3C3B6E,Dubby twilight,images/centroid_donut_dy0Fv_wI55.png,tables/table_freq_dy0Fv_wI55.csv,images/dbs_plot_dy0Fv_wI55.png,images/key_and_id_dy0Fv_wI55.png,3e860f3930474d27a7c04466268b66047dc69981defccd...

In [9]:
df['ID'].is_unique

False

In [10]:
df[df['ID'].duplicated(keep=False)]

,Path,temp_id,file_name,Extension,dur_seconds,dur_min,sr,bit_depth,bit_rate,channels,file_size,file_size_human,num_frames,error,ms_lufs,ms_LUFS_code,id_cat_lufs,mean_bpm,std_bpm,min_bpm,max_bpm,variation_percentage,dominant_bpm,bpm_consistency,bpm_consistency_cat,title,title_file,artist,artist_file,LABEL,label_file,genre,genre_file,rel_year,rel_year_file,KEY,key_file,mix_name,remixer,remix,date_purchased,rel_date,rel_date_file,key_dj,key_music,status,Relative_Key,Key_Up,Key_Down,Jaw_s_Mix,Mood_Shifter,ID,comment,Path_jpg_album,Path_jpg_key,Path_jpg_clip,Path_png_bar_dyn,ms_LUFS_norm,Path_png_bar_lufs,Spectral_Bandwidth,Spectral_Flatness,HEX_shape_texture,Path_png_bar_text,spec_centroid_hz,centroid_color,centroid_desc,Path_png_bar_centroid,Path_csv_freq,Path_png_dr,Path_png_id_and_key,audio_hash
260,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2023_this/_23_10_Detroit_Hou_Tech/TRkw_Strut_ARkw_Rick_Marshall_MXkw_Original_Mix_KYkw_E_Minor_BPkw_124_GNkw_Jackin_House_RMkw__LBkw_Whitebeard_Records_RYkw_2015_11_27_PYkw_2023_10_16.aiff,TRkw_Strut_ARkw_Rick_Marshall_MXkw_Original_Mix_KYkw_E_Minor_BPkw_124_GNkw_Jackin_House_RMkw__LBkw_Whitebeard_Records_RYkw_2015_11_27_PYkw_2023_10_16,TRkw_Strut_ARkw_Rick_Marshall_MXkw_Original_Mix_KYkw_E_Minor_BPkw_124_GNkw_Jackin_House_RMkw__LBkw_Whitebeard_Records_RYkw_2015_11_27_PYkw_2023_10_16.aiff,.aiff,439.518073,7.325301,44100,16,None,2,77760244,74.16 MB,19382747,None,-8.066,W,W,124.497428,1.499738e+00,123.046875,126.048018,1.204634e+00,123,51.666667,D_6,Strut Original Mix,ID3TAGS,Rick Marshall,ID3TAGS,Whitebeard Records,ID3TAGS,Jackin House,ID3TAGS,2015,ID3TAGS,Gmin,ID3TAGS,Original_Mix,Original Mix,U,2023-10-16,2015-11-27,ID3TAGS,6A,Gmin,Success: TKEY updated,6B,7A,5A,1A,9B,dy6Fw_sR77,dy6Fw_sR77_Gmin,images/cover_1_dy6Fw_sR77.jpg,images/key_plotdy6Fw_sR77.png,images/clip_plotdy6Fw_sR77.jpg,images/bpm_bar_dyn_dy6Fw_sR77.png,88.461538,images/lufs_bar_dyn_dy6Fw_sR77.png,3656.896383,0.019276,#001a6e,images/text_shape_dy6Fw_sR77.png,3839.435147,#CC7722,Muted emotion,images/centroid_donut_dy6Fw_sR77.png,tables/table_freq_dy6Fw_sR77.csv,images/dbs_plot_dy6Fw_sR77.png,images/key_and_id_dy6Fw_sR77.png,76d7356526ac4cf395f566a0672c563c0ad4527a830c803b424b2c4d05dc1b0e
261,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2023_this/_23_10_Detroit_Hou_Tech/TRkw_Strut_ARkw_Rick_Marshall_MXkw_Original_Mix_KYkw_E_Minor_BPkw_124_GNkw_Jackin_House_RMkw__LBkw_Whitebeard_Records_RYkw_2016_12_02_PYkw_2023_10_16.aiff,TRkw_Strut_ARkw_Rick_Marshall_MXkw_Original_Mix_KYkw_E_Minor_BPkw_124_GNkw_Jackin_House_RMkw__LBkw_Whitebeard_Records_RYkw_2016_12_02_PYkw_2023_10_16,TRkw_Strut_ARkw_Rick_Marshall_MXkw_Original_Mix_KYkw_E_Minor_BPkw_124_GNkw_Jackin_House_RMkw__LBkw_Whitebeard_Records_RYkw_2016_12_02_PYkw_2023_10_16.aiff,.aiff,439.518073,7.325301,44100,16,None,2,77779556,74.18 MB,19382747,None,-8.066,W,W,124.497428,1.499738e+00,123.046875,126.048018,1.204634e+00,123,51.666667,D_6,Strut Original Mix,ID3TAGS,Rick Marshall,ID3TAGS,Whitebeard Records,ID3TAGS,Jackin House,ID3TAGS,2016,ID3TAGS,Gmin,ID3TAGS,Original_Mix,Original Mix,U,2023-10-16,2016-12-02,ID3TAGS,6A,Gmin,Success: TKEY updated,6B,7A,5A,1A,9B,dy6Fw_sR77,dy6Fw_sR77_Gmin,images/cover_1_dy6Fw_sR77.jpg,images/key_plotdy6Fw_sR77.png,images/clip_plotdy6Fw_sR77.jpg,images/bpm_bar_dyn_dy6Fw_sR77.png,88.461538,images/lufs_bar_dyn_dy6Fw_sR77.png,3656.896383,0.019276,#001a6e,images/text_shape_dy6Fw_sR77.png,3839.435147,#CC7722,Muted emotion,images/centroid_donut_dy6Fw_sR77.png,tables/table_freq_dy6Fw_sR77.csv,images/dbs_plot_dy6Fw_sR77.png,images/key_and_id_dy6Fw_sR77.png,76d7356526ac4cf395f566a0672c563c0ad4527a830c803b424b2c4d05dc1b0e
298,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2023_this/_23_11_AN_SpotLite/TRkw_Sigilo_ARkw_Salvador_Pacheco_MXkw_Original_Mix_KYkw_Db_Minor_BPkw_126_GNkw_Minimal___Deep_Tech_RMkw__LBkw_Privilege_RYkw_2011_12_21_PYkw_2023_11_29.aiff,TRkw_Sigilo_ARkw_Salvador_Pacheco_MXkw_Original_Mix_KYkw_Db_Minor_BPkw_126_GNkw_Minimal___Deep_Tech_RMkw__LBkw_Privilege_RYkw_2011_12_21_PYkw_2023_11_29,TRkw_Sigilo_ARkw_Salvador_Pacheco_MXkw_Original_Mix_KYkw_Db_Minor_BPkw_126_GNkw_Minimal___Deep_Tech_RMkw__LBkw_Privilege_RYkw_2011_12_21_PYkw_2023_11_29.aiff,.aiff,431.070862,7.184514,44100,16,None,2,76070862,72.55 MB,19010225,None,-9.403,V,V,126.048018,1.421085e-14,126.048018,126.048018,1.127416e-14,126,100.000000,D_0,Sigilo Original Mix,ID3TAGS,Salvador Pacheco,ID3TAGS,Privilege,ID3TAGS,Minimal / Deep Tech,ID3TAGS,2011,ID3TAGS,Amin,ID3TAGS,Original_Mix,Original Mix,U,2023-11-29,2011-12-21,ID3TAGS,8A,Amin,Success: TKEY updated,8B,9A,7A,3A,11B,dy0Fv_sS76,dy0Fv_sS76_Amin,images/cover_1_dy0Fv_sS76.jpg,images/key_plotdy0Fv_sS76.png,images/clip_plotdy0Fv_sS76.jpg,images/bpm_bar_dyn_dy0Fv_sS76.png,84.615385,images/lufs_bar_dyn_dy0Fv_sS76.png,4087.172648,0.003886,#001a6e,images/text_shape_dy0Fv_sS76.png,2558.625035,#3C3B6E,Dubby twilight,images/centroid_donut_dy0Fv_sS76.png,tables/table_freq_dy0Fv_sS76.csv,images/dbs_plot_dy0Fv_sS76.png,images/key_and_id_dy0Fv_sS76.png,155f56a75a132ce1ddbc423d5f262387242a96681b1709ae6da2e25b55956d91
356,"/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2024_this/__24_04_NorthL_BadBunny_LatinFast/TRkw_We_Like_To_Part_ARkw_Plush_Managements_Inc.,_DJ_Chrysalis,_Regfant_MXkw_Original_KYkw_Ab_Major_BPkw_130_GNkw_House_RMkw__LBkw_Plush_Records_Inc._RYkw_2021_05_12_PYkw_2024_04_03.aiff","TRkw_We_Like_To_Part_ARkw_Plush_Managements_Inc.,_DJ_Chrysalis,_Regfant_MXkw_Original_KYkw_Ab_Major_BPkw_130_GNkw_House_RMkw__LBkw_Plush_Records_Inc._RYkw_2021_05_12_PYkw_2024_04_03","TRkw_We_Like_To_Part_ARkw_Plush_Managements_Inc.,_DJ_Chrysalis,_Regfant_MXkw_Original_KYkw_Ab_Major_BPkw_130_GNkw_House_RMkw__LBkw_Plush_Records_Inc._RYkw_2021_05_12_PYkw_2024_04_03.aiff",.aiff,371.076939,6.184616,44100,16,None,2,66341934,63.27 MB,16364493,None,-11.750,T,T,129.199219,0.000000e+00,129.199219,129.199219,0.000000e+00,129,100.000000,D_0,We Like To Part Original,ID3TAGS,Plush Managements Inc DJ Chrysalis Regfant,ID3TAGS,Plush Records Inc.,ID3TAGS,House,ID3TAGS,2021,ID3TAGS,Cmin,ID3TAGS,Original,Original,U,2024-04-03,2021-05-12,ID3TAGS,5A,Cmin,Success: TKEY updated,5B,6A,4A,12A,8B,dy0Et_wP66,dy0Et_wP66_Cmin,images/cover_1_dy0Et_wP66.jpg,images/key_plotdy0Et_wP66.png,images/clip_plotdy0Et_wP66.jpg,images/bpm_bar_dyn_dy0Et_wP66.png,76.923077,images/lufs_bar_dyn_dy0Et_wP66.png,3063.412199,0.007631,#0039a6,images/text_shape_dy0Et_wP66.png,2603.362041,#3C3B6E,Dubby twilight,images/centroid_donut_dy0Et_wP66.png,tables/table_freq_dy0Et_wP66.csv,images/dbs_plot_dy0Et_wP66.png,images/key_and_id_dy0Et_wP66.png,1053fc7b9acd4a68d0911382f6e9bffca723a1a73d0adc4a801dab1c11c2e958
409,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2024_this/__24_05_MVMNT_block_is_HOT/TRkw_The_Stranger_ARkw_Mike_Huckaby_MXkw_Original_Mix_KYkw_C_Minor_BPkw_127_GNkw_House_RMkw__LBkw_Cross_Section_Music_RYkw_2009_09_02_PYkw_2024_12_02.aiff,TRkw_The_Stranger_ARkw_Mike_Huckaby_MXkw_Original_Mix_KYkw_C_Minor_BPkw_127_GNkw_House_RMkw__LBkw_Cross_Section_Music_RYkw_2009_09_02_PYkw_2024_12_02,TRkw_The_Stranger_ARkw_Mike_Huckaby_MXkw_Original_Mix_KYkw_C_Minor_BPkw_127_GNkw_House_RMkw__LBkw_Cross_Section_Music_RYkw_2009_09_02_PYkw_2024_12_02.aiff,.aiff,368.614558,6.143576,44100,16,None,2,65053474,62.04 MB,16255902,None,-9.314,V,V,126.048018,1.421085e-14,126.048018,126.048018,1.127416e-14,126,100.000000,D_0,The Stranger Original Mix,ID3TAGS,Mike Huckaby,ID3TAGS,Cross Section Music,ID3TAGS,House,ID3TAGS,2009,ID3TAGS,Amin,ID3TAGS,Original_Mix,Original Mix,U,2024-12-02,2009-09-02,ID3TAGS,8A,Amin,Success: TKEY updated,8B,9A,7A,3A,11B,dy0Fv_tM65,dy0Fv_tM65_Amin,images/cover_1_dy0Fv_tM65.jpg,images/key_plotdy0Fv_tM65.png,images/clip_plotdy0Fv_tM65.jpg,images/bpm_bar_dyn_dy0Fv_tM65.png,84.615385,images/lufs_bar_dyn_dy0Fv_tM65.png,3946.382331,0.010405,#001a6e,images/text_shape_dy0Fv_tM65.png,4760.963114,#F08080,Emotional but soft,images/centroid_donut_dy0Fv_tM65.png,tables/table_freq_dy0Fv_tM65.csv,images/dbs_plot_dy0Fv_tM65.png,images/key_and_id_dy0Fv_tM65.png,2ff6f398b36cb95713289767fdc2b38335e42abdb9688bea43457628799e88ae
582,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2024_this/__24_06_Metroplex_2_and_RNDMgood/TRkw_The_Tresor_Track_ARkw_Mike_Huckaby_MXkw_Original_Mix_KYkw_D_Minor_BPkw_129_GNkw_Techno_(Raw___Deep___Hypnotic)_RMkw__LBkw_Tresor_Records_RYkw_2011_10_31_PYkw_2024_12_02.aiff,TRkw_The_Tresor_Track_ARkw_Mike_Huckaby_MXkw_Original_Mix_KYkw_D_Minor_BPkw_129_GNkw_Techno_(Raw___Deep___Hypnotic)_RMkw__LBkw_Tresor_Records_RYkw_2011_10_31_PYkw_2024_12_02,TRkw_The_Tresor_Track_ARkw_Mike_Huckaby_MXkw_Original_Mix_KYkw_D_Minor_BPkw_129_GNkw_Techno_(Raw___Deep___Hypnotic)_RMkw__LBkw_Tresor_Records_RYkw_2011_10_31_PYkw_2024_12_02.aiff,.aiff,384.382653,6.406378,44100,16,None,2,67871952,64.73 MB,16951275,None,-9.734,V,V,129.199219,0.000000e+00,129.199219,129.199219,0.000000e+00,129,100.000000,D_0,The Tresor Track Original Mix,ID3TAGS,Mike Huckaby,ID3TAGS,Tresor Records,ID3TAGS,Techno (Raw / Deep / Hypnotic),ID3TAGS,2011,ID3TAGS,Gmin,ID3TAGS,Original_Mix,Original Mix,U,2024-12-02,2011-10-31,FILE_NAME,6A,Gmin,Success: TKEY updated,6B,7A,5A,1A,9B,dy0Fv_tM67,dy0Fv_tM67_Gmin,images/cover_1_dy0Fv_tM67.jpg,images/key_plotdy0Fv_tM67.png,images/clip_plotdy0Fv_tM67.jpg,images/bpm_bar_dyn_dy0Fv_tM67.png,84.615385,images/lufs_bar_dyn_dy0Fv_tM67.png,3628.545930,0.008463,#001a6e,images/text_shape_dy0Fv_tM67.png,3048.468022,#556B2F,"Organic, earthy",images/centroid_donut_dy0Fv_tM67.png,tables/table_freq_dy0Fv_tM67.csv,images/dbs_plot_dy0Fv_tM67.png,images/key_and_id_dy0Fv_tM67.png,b5733e9b87a8758f9ebce62a7c22a2032f5832c59746ea9ad0a24c96f0d051c3
583,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2024_this/__24_06_Metroplex_2_and_RNDMgood/TRkw_The_Tresor_Track_ARkw_Mike_Huckaby_MXkw_Original_Mix_KYkw_D_Minor_BPkw_129_GNkw_Techno_(Raw___Deep___Hypnotic)_RMkw__LBkw_Tresor_Records_RYkw_2012_07_30_PYkw_2024_12_02.aiff,TRkw_The_Tresor_Track_ARkw_Mike_Huckaby_MXkw_Original_Mix_KYkw_D_Minor_BPkw_129_GNkw_Techno_(Raw___Deep___Hypnotic)_RMkw__LBkw_Tresor_Records_RYkw_2012_07_30_PYkw_2024_12_02,TRkw_The_Tresor_Track_ARkw_Mike_Huckaby_MXkw_Original_Mix_KYkw_D_Minor_BPkw_129_GNkw_Techno_(Raw___Deep___Hypnotic)_RMkw__LBkw_Tresor_Records_RYkw_2012_07_30_PYkw_2024_12_02.aiff,.aiff,384.382653,6.406378,44100,16,None,2,67859270,64.72 MB,16951275,None,-9.734,V,V,129.199219,0.000000e+00,129.199219,129.199219,0.000000e+00,129,100.000000,D_0,The Tresor Track Original Mix,ID3TAGS,Mike Huckaby,ID3TAGS,Tresor Records,ID3TAGS,Techno (Raw / Deep / Hypnotic),ID3TAGS,2012,ID3TAGS,Gmin,ID3TAGS,Original_Mix,Original Mix,U,2024-12-02,2012-07-30,FILE_NAME,6A,Gmin,Success: TKEY updated,6B,7A,5A,1A,9B,dy0Fv_tM67,dy0Fv_tM67_Gmin,images/cover_1_dy0Fv_tM67.jpg,images/key_plotdy0Fv_tM67.png,images/clip_plotdy0Fv_tM67.jpg,images/bpm_bar_dyn_dy0Fv_tM67.png,84.615385,images/lufs_bar_dyn_dy0Fv_tM67.png,3628.545930,0.008463,#001a6e,images/text_shape_dy0Fv_tM67.png,3048.468022,#556B2F,"Organic, earthy",images/centroid_donut_dy0Fv_tM67.png,tables/table_freq_dy0Fv_tM67.csv,images/dbs_plot_dy0Fv_tM67.png,images/key_and_id_dy0Fv_tM67.png,b5733e9b87a8758f9ebce62a7c22a2032f5832c59746ea9ad0a24c96f0d051c3
611,"/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2024_this/__24_07_Puma_BurningMan_indian/TRkw_Sei_Yona_ARkw_Sababa_5,_Shiran_Tzfira_MXkw_Manqo_Remix_KYkw_C_Minor_BPkw_139_GNkw_Nu_Disco___Disco_RMkw_MANQO_LBkw_Batov_Records_RYkw_2023_09_13_PYkw_2024_12_02.aiff","TRkw_Sei_Yona_ARkw_Sababa_5,_Shiran_Tzfira_MXkw_Manqo_Remix_KYkw_C_Minor_BPkw_139_GNkw_Nu_Disco___Disco_RMkw_MANQO_LBkw_Batov_Records_RYkw_2023_09_13_PYkw_2024_12_02","TRkw_Sei_Yona_ARkw_Sababa_5,_Shiran_Tzfira_MXkw_Manqo_Remix_KYkw_C_Minor_BPkw_139_GNkw_Nu_Disco___Disco_RMkw_MANQO_LBkw_Batov_Records_RYkw_2023_09_13_PYkw_2024_12_02.aiff",.aiff,347.273379,5.78789,44100,16,None,2,62032088,59.16 MB,15314756,None,-10.703,U,U,132.512019,5.684342e-14,132.512019,132.512019,4.289680e-14,133,100.000000,D_0,Sei Yona Manqo Remix,ID3TAGS,Sababa 5 Shiran Tzfira,ID3TAGS,Batov Records,ID3TAGS,Nu Disco / Disco,ID3TAGS,2023,ID3TAGS,Gmin,ID3TAGS,Manqo_Remix,Manqo Remix MANQO,R,2024-12-02,2023-09-13,ID3TAGS,6A,Gmin,Success: TKEY updated,6B,7A,5A,1A,9B,dy0Eu_sS62,dy0Eu_sS62_Gmin,images/cover_1_dy0Eu_sS62.jpg,images/key_plotdy0Eu_sS62.png,images/clip_plotdy0Eu_sS62.jpg,images/bpm_bar_dyn_dy0Eu_sS62.png,80.769231,images/lufs_bar_dyn_dy0Eu_sS62.png,3435.756017,0.005820,#0039a6,images/text_shape_dy0Eu_sS62.png,2883.669972,#014421,"Jungle, tribal pulse",images/centroid_donut_dy0Eu_sS62.png,tables/table_freq_dy0Eu_sS62.csv,images/dbs_plot_dy0Eu_sS62.png,images/key_and_id_dy0Eu_sS62.png,105c848350ecf568f8d48bc9883b4b5b08244158744e2acc4e8f18ba4e5e6cb9
645,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2024_this/__24_08_Barefoot_and_FREE/TRkw_The_Alchemy_of_Circumstance_ARkw_Midland_MXkw_Original_Mix_KYkw_Db_Minor_BPkw_96_GNkw_Electronica_RMkw__LBkw_Graded_Records_RYkw_2019_10_30_PYkw_2024_12_02.aiff,TRkw_The_Alchemy_of_Circumstance_ARkw_Midland_MXkw_Original_Mix_KYkw_Db_Minor_BPkw_96_GNkw_Electronica_RMkw__LBkw_Graded_Records_RYkw_2019_10_30_PYkw_2024_12_02,TRkw_The_Alchemy_of_Circumstance_ARkw_Midland_MXkw_Original_Mix_KYkw_Db_Minor_BPkw_96_GNkw_Electronica_RMkw__LBkw_Graded_Records_RYkw_2019_10_30_PYkw_2024_12_02.aiff,.aiff,346.16,5.769333,44100,16,None,2,65078158,62.06 MB,15265656,None,-9.467,V,V,123.046875,0.000000e+00,123.046875,123.046875,0.000000e+00,123,100.000000,D_0,The Alchemy of Circumstance Original Mix,ID3TAGS,Midland,ID3TAGS,Graded Records,ID3TAGS,Electronica,ID3TAGS,2019,ID3TAGS,Amin,ID3TAGS,Original_Mix,Original Mix,U,2024-12-02,2019-10-30,ID3TAGS,8A,Amin,Success: TKEY updated,8B,9A,7A,3A,11B,dy0Fv_tM65,dy0Fv_tM65_Amin,images/cover_1_dy0Fv_tM65.jpg,images/key_plotdy0Fv_tM65.png,images/clip_plotdy0Fv_tM65.jpg,images/bpm_bar_dyn_dy0Fv_tM65.png,84.615385,images/lufs_bar_dyn_dy0Fv_tM65.png,2290.810694,0.010929,#0039a6,images/text_shape_dy0Fv_tM65.png,1848.338175,#800000,"Intense, emotional",images/centroid_donut_dy0Fv_tM65.png,tables/table_freq_dy0Fv_tM65.csv,images/dbs_plot_dy0Fv_tM65.png,images/key_and_id_dy0Fv_tM65.png,fa6c59920d698926622f25a2b68bcc491752728861091eb9d3610a737aacd400
834,"/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2024_this/__24_12_NYE_25/TRkw_Screen_Off_(feat._Ras_Stimulant)_ARkw_Session_Victim,_Ras_Stimulant_MXkw_Original_Mix_KYkw_D_Major_BPkw_123_GNkw_Nu_Disco___Disco_RMkw__LBkw_Delusions_Of_Grandeur_RYkw_2024_06_21_PYkw_2024_12_31.aiff","TRkw_Screen_Off_(feat._Ras_Stimulant)_ARkw_Session_Victim,_Ras_Stimulant_MXkw_Original_Mix_KYkw_D_Major_BPkw_123_GNkw_Nu_Disco___Disco_RMkw__LBkw_Delusions_Of_Grandeur_RYkw_2024_06_21_PYkw_2024_12_31","TRkw_Screen_Off_(feat._Ras_Stimulant)_ARkw_Session_Victim,_Ras_Stimulant_MXkw_Original_Mix_KYkw_D_Major_BPkw_123_GNkw_Nu_Disco___Disco_RMkw__LBkw_Delusions_Of_Grandeur_RYkw_2024_06_21_PYkw_2024_12_31.aiff",.aiff,350.390975,5.83985,44100,16,None,2,62886920,59.97 MB,15452242,None,-10.272,U,U,123.046875,0.000000e+00,123.046875,123.046875,0.000000e+00,123,100.000000,D_0,Screen Off feat Ras Stimulant Original Mix,ID3TAGS,Session Victim Ras Stimulant,ID3TAGS,Delusions Of Grandeur,ID3TAGS,Nu Disco / Disco,ID3TAGS,2024,ID3TAGS,Dmin,ID3TAGS,Original_Mix,Original Mix,U,2024-12-31,2024-06-21,ID3TAGS,7A,Dmin,Success: TKEY updated,7B,8A,6A,2A,10B,dy0Eu_sS62,dy0Eu_sS62_Dmin,images/cover_1_dy0Eu_sS62.jpg,images/key_plotdy0Eu_sS62.png,images/clip_plotdy0Eu_sS62.jpg,images/bpm_bar_dyn_dy0Eu_sS62.png,80.769231,images/lufs_bar_dyn_dy0Eu_sS62.png,5270.218519,0.011810,#001a6e,images/text_shape_dy0Eu_sS62.png,4150.525562,#FF7034,Heated drama,images/centroid_donut_dy0Eu_sS62.png,tables/table_freq_dy0Eu_sS62.csv,images/dbs_plot_dy0Eu_sS62.png,images/key_and_id_dy0Eu_sS62.png,b1a84c6e5b2eec73c77e55d56c389b3d0a36c9033a51501a1b5c2300244a3496
1018,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2025_this/__25_04_BP_LATIN_HOUSE/TRkw_Warm_Time_ARkw_Ponty_Mython_MXkw_Arsenii_Remix_KYkw_A_Minor_BPkw_113_GNkw_Indie_Dance_RMkw_Arsenii_LBkw_Beats_Delivery_RYkw_2013_03_02_PYkw_2025_04_04.aiff,TRkw_Warm_Time_ARkw_Ponty_Mython_MXkw_Arsenii_Remix_KYkw_A_Minor_BPkw_113_GNkw_Indie_Dance_RMkw_Arsenii_LBkw_Beats_Delivery_RYkw_2013_03_02_PYkw_2025_04_04,TRkw_Warm_Time_ARkw_Ponty_Mython_MXkw_Arsenii_Remix_KYkw_A_Minor_BPkw_113_GNkw_Indie_Dance_RMkw_Arsenii_LBkw_Beats_Delivery_RYkw_2013_03_02_PYkw_2025_04_04.aiff,.aiff,375.884626,6.264744,44100,16,None,2,66342130,63.27 MB,16576512,None,-11.770,T,T,112.347147,0.000000e+00,112.347147,112.347147,0.000000e+00,112,100.000000,D_0,Warm Time Arsenii Remix,ID3TAGS,Ponty Mython,ID3TAGS,Beats Delivery,ID3TAGS,Indie Dance,ID3TAGS,2013,ID3TAGS,Amin,ID3TAGS,Arsenii_Remix,Arsenii Remix Arsenii,R,2025-04-04,2013-03-02,ID3TAGS,8A,Amin,Success: TKEY updated,8B,9A,7A,3A,11B,dy0Et_wP66,dy0Et_wP66_Amin,images/cover_1_dy0Et_wP66.jpg,images/key_plotdy0Et_wP66.png,images/clip_plotdy0Et_wP66.jpg,images/bpm_bar_dyn_dy0Et_wP66.png,76.923077,images/lufs_bar_dyn_dy0Et_wP66.png,4178.650666,0.025231,#001a6e,images/text_shape_dy0Et_wP66.png,4458.583944,#FFD700,Emotional climax,images/centroid_donut_dy0Et_wP66.png,tables/table_freq_dy0Et_wP66.csv,images/dbs_plot_dy0Et_wP66.png,images/key_and_id_dy0Et_wP66.png,f8cfb09a63b7e0a7bc8a9b5adf4be0a40ce4f21281e39fa06df91ff035b5350a
1083,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2025_this/__25_04_BP_ximMAYBDAY_HOUSY_PARTY_LATIN/TRkw_Shakedown_ARkw_Satoshi_Tomiie_MXkw_Original_Mix_KYkw_E_Minor_BPkw_124_GNkw_House_RMkw__LBkw_Phonogramme_RYkw_2024_07_05_PYkw_2025_04_16.aiff,TRkw_Shakedown_ARkw_Satoshi_Tomiie_MXkw_Original_Mix_KYkw_E_Minor_BPkw_124_GNkw_House_RMkw__LBkw_Phonogramme_RYkw_2024_07_05_PYkw_2025_04_16,TRkw_Shakedown_ARkw_Satoshi_Tomiie_MXkw_Original_Mix_KYkw_E_Minor_BPkw_124_GNkw_House_RMkw__LBkw_Phonogramme_RYkw_2024_07_05_PYkw_2025_04_16.aiff,.aiff,435.313333,7.255222,44100,16,None,2,76998796,73.43 MB,19197318,None,-9.260,V,V,123.046875,0.000000e+00,123.046875,123.046875,0.000000e+00,123,100.000000,D_0,Shakedown Original Mix,ID3TAGS,Satoshi Tomiie,ID3TAGS,Phonogramme,ID3TAGS,House,ID3TAGS,2024,ID3TAGS,F#min,ID3TAGS,Original_Mix,Original Mix,U,2025-04-16,2024-07-05,ID3TAGS,11A,F#min,Success: TKEY updated,11B,12A,10A,6A,2B,dy0Fv_sS76,dy0Fv_sS76_F#min,images/cover_1_dy0Fv_sS76.jpg,images/key_plotdy0Fv_sS76.png,images/clip_plotdy0Fv_sS76.jpg,images/bpm_bar_dyn_dy0Fv_sS76.png,84.615385,images/lufs_bar_dyn_dy0Fv_sS76.png,3548.954308,0.016553,#0039a6,images/text_shape_dy0Fv_sS76.png,3489.856264,#808000,"Tense, decaying",images/centroid_donut_dy0Fv_sS76.png,tables/table_freq_dy0Fv_sS76.csv,images/dbs_plot_dy0Fv_sS76.png,images/key_and_id_dy0Fv_sS76.png,0f08f3727216b2669e0b9ada961ba64d47d03fedf9d473c4daa842fef9a87873
1086,/Volumes/MUSIC_PROD/_1_NEW_SOURCE/_2025_this/__25_04_BP_ximMAYBDAY_HOUSY_PARTY_LATIN/TRkw_Slow_Bender_ARkw_25_Places_MXkw_Original_Mix_KYkw_Ab_Minor_BPkw_114_GNkw_Deep_House_RMkw__LBkw_Liebe_Detail_RYkw_2012_06_04_PYkw_2025_04_16.aiff,TRkw_Slow_Bender_ARkw_25_Places_MXkw_Original_Mix_KYkw_Ab_Minor_BPkw_114_GNkw_Deep_House_RMkw__LBkw_Liebe_Detail_RYkw_2012_06_04_PYkw_2025_04_16,TRkw_Slow_Bender_ARkw_25_Places_MXkw_Original_Mix_KYkw_Ab_Minor_BPkw_114_GNkw_Deep_House_RMkw__LBkw_Liebe_Detail_RYkw_2012_06_04_PYkw_2025_04_16.aiff,.aiff,378.947392,6.31579,44100,16,None,2,66886210,63.79 MB,16711580,None,-9.510,V,V,116.987327,8.663162e+00,114.843750,151.999081,7.405214e+00,115,94.230769,D_3,Slow Bender Original Mix,ID3TAGS,25 Places,ID3TAGS,Liebe Detail,ID3TAGS,Deep House,ID3TAGS,2012,ID3TAGS,G#min,ID3TAGS,Original_Mix,Original Mix,U,2025-04-16,2012-06-04,ID3TAGS,1A,G#min,Success: TKEY updated,1B,2A,12A,8A,4B,dy3Fv_s266,dy3Fv_s266_G#min,images/cover_1_dy3Fv_s266.jpg,images/key_plotdy3Fv_s266.png,images/clip_plotdy3Fv_s266.jpg,images/bpm_bar_dyn_dy3Fv_s266.png,84.615385,images/lufs_bar_dyn_dy3Fv_s266.png,3752.302496,0.012209,#001a6e,images/text_shape_dy3Fv_s266.png,3105.129313,#556B2F,"Organic, earthy",images/centroid_donut_dy3Fv_s266.png,tables/table_freq_dy3Fv_s266.csv,images/dbs_plot_dy3Fv_s266.png,images/key_and_id_dy3Fv_s266.png,51fd8ce35bd53b8c9eb975e7801870bd00fd1ad5d9ccf4041556229edf9407d5

In [11]:
folders = ['/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2023_this/_23_02_AN_LA_VENTANA', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2023_this/_23_03_Love_Lang', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2023_this/_23_04_Foundation_Hotel', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2023_this/_23_04_NEW_LODGE', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2023_this/_23_05_AN_bigPINK', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2023_this/_23_06_ttt_SPKRBOX', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2023_this/_23_08_Barefoot', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2023_this/_23_08_SL_ACAPELLAS', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2023_this/_23_09_AN_ArtPArk', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2023_this/_23_10_Detroit_Hou_Tech', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2023_this/_23_11_AN_SpotLite', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2023_this/_23_12_Tangent_Debout', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_04_BBssBBssBBs_BandCamp', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_04_NorthL_BadBunny_LatinFast', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_05_MVMNT_block_is_HOT', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_06_Detroit_Brazil_Funky', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_06_Metroplex_1_and_RNDMgood', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_06_Metroplex_2_and_RNDMgood', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_07_Puma_BurningMan_indian', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_08_Barefoot_and_FREE', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_08_Xime_13_Memorial', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_09_Eagle_SPKR_Techno', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_09_Ghettotech_HiTECH_stu', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_11_11_N0_Supervisi0n_SPKRbox', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_11_11_albm_LordECHO_JAZZ', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_11_11_albm_MimSuleiman_TRIBAL', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_11_Dinner_Materia_Puma_Jazzy', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_12_Dinner_HipHop_Indian_Puma', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_12_NYE_25', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/__24_12_fixed_and_added', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/___DJ_friends_Nun', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2024_this/___YODJ_N0Supervisi0n', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2025_this/__25_02_CDMX_SecretoRoom', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2025_this/__25_02_DETROIT_PUMA_SPKR', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2025_this/__25_03_CAPSULE_House_Latin', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2025_this/__25_04_BCAL_SalsaEstrellasPa', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2025_this/__25_04_BCAL_TerapiaLatina', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2025_this/__25_04_BP_LATIN_HOUSE', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2025_this/__25_04_BP_Rapharazzi_BDAY', '/Volumes/MUSIC_PROD/_1_NEW_SOURCE_this/_2025_this/__25_04_BP_ximMAYBDAY_HOUSY_PARTY_LATIN']

len(folders)

40