In [1]:
my_aiff = "/Users/yerik/Music/_1_NEW_SOURCE"
#"/Users/yerik/Downloads/try_py_AIFF/folders"
exec(open("_fns.py",encoding="utf-8").read())

Searching for Files: 100%|█████████████████████████████████████████| 1120/1120 [00:00<00:00, 161569.06files/s]

ATTN ::: <E>  AFTER making sure that you have assigned the DIRECTORY PATH to ::: var ::: /Users/yerik/Music/_1_NEW_SOURCE
***df*** will be returned having ::: 1108  rows, write df in next cell to see your DATA FRAME

second part FREQUENCIES OF df :::

Grand Total Size in MB: 67414.125
Grand Total Size in Bytes: 70688833386.000
Grand Total Size in GB: 65.834

 FREQUENCY TABLE:::

  Extension  frequency  total_size_in_mb
0     .aiff       1108      67414.124857

In [3]:
df = _titile_0204_id3_filefallback_GET_df_with_titile(df, 'title', 'TRkw', 'ARkw')

Extracting ID3 Titles: 100%|█████████████████████████████████████████████| 1108/1108 [00:01<00:00, 961.36it/s]

In [4]:
print(df['title_file'].value_counts())

n    941
y    167
Name: title_file, dtype: int64

In [8]:
df_no_extracted_title = df[df['temp_id'].str.contains(r'RMkw\s*LBkw', na=False)]
df_no_extracted_title[['temp_id', 'Path']]
#'RMkw' ; btw_back = 'LBkw'

Empty DataFrame
Columns: [temp_id, Path]
Index: []

In [12]:
import re

def has_empty_title_between_keys(temp_id, front, back):
    if isinstance(temp_id, str) and front in temp_id and back in temp_id:
        start = temp_id.find(front) + len(front)
        end = temp_id.find(back, start)
        content = temp_id[start:end].strip('_ ').lower()
        return content == ''
    return False

# Set your markers
btw_front = 'RMkw'
btw_back = 'LBkw'

# Find where there's nothing in between
df_empty_titles = df[df['temp_id'].apply(lambda x: has_empty_title_between_keys(x, btw_front, btw_back))]
df_empty_titles[['temp_id', 'Path']]

,temp_id,Path
0,TRkw_Revox_ARkw_Tim_Green_MXkw_Original_Mix_KY...,/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_2...
4,TRkw_Recovery_ARkw_Rival_Consoles_MXkw_Origina...,/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_2...
5,TRkw_Final_Credits_ARkw_Midland_MXkw_Original_...,/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_2...
6,TRkw_Purple_Drank_ARkw_Axel_Boman_MXkw_Origina...,/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_2...
7,TRkw_Let_s_Dream_ARkw_Paco_Osuna_MXkw_Original...,/Users/yerik/Music/_1_NEW_SOURCE/_2023_this/_2...
...,...,...
1102,TRkw_Every_Body_s_A_Star_ARkw_Javonntte_MXkw_O...,/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__...
1103,TRkw_Loose_Legs_ARkw_Demuja_MXkw_Original_Mix_...,/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__...
1104,TRkw_Girls_Like_Us_ARkw_Fez_MXkw_Original_Mix_...,/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__...
1105,"TRkw_Deviate_ARkw_Manuel_Tur,_DPlay,_Manuel_Tu...",/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__...
1106,"TRkw_Fire_ARkw_Mark_Broom,_Riva_Starr,_Star_B_...",/Users/yerik/Music/_1_NEW_SOURCE/_2024_this/__...